### ISSUE TITLE
I am getting error "Fatal error: Uncaught SoapFault exception: [soap:Client]"

### ISSUE THREAD

**Issue by wdraghwendra** [christoph-schaeffer/dhl-business-shipping#13]
Fatal error: Uncaught SoapFault exception: [soap:Server] UNKNOWN_ERROR in <local directory>\vendor\christoph-schaeffer\dhl-business-shipping\src\Soap.php:53 Stack trace: #0 <local directory>\vendor\christoph-schaeffer\dhl-business-shipping\src\Soap.php(53): SoapClient->__call('createShipmentO...', Array) #1 <local directory>\vendor\christoph-schaeffer\dhl-business-shipping\src\Client.php(73): ChristophSchaeffer\Dhl\BusinessShipping\Soap->callSoapFunction('createShipmentO...', Object(ChristophSchaeffer\Dhl\BusinessShipping\Request\createShipmentOrder)) #2 <local directory>\dhl.php(71): ChristophSchaeffer\Dhl\BusinessShipping\Client->createShipmentOrder(Object(ChristophSchaeffer\Dhl\BusinessShipping\Request\createShipmentOrder)) #3 {main} thrown in <local directory>\vendor\christoph-schaeffer\dhl-business-shipping\src\Soap.php on line 53

Please guide

**Comment by ahmadtechnik** [comment]
me too,

I think the problem from DHL servers. 
This library has nothing to do  with this error.
